# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# Minimal configuration for getting started
language: "en-US"
reviews:
  collapse_walkthrough: false
  profile: "chill"
  high_level_summary: true
  request_changes_workflow: true
  poem: false
  in_progress_fortune: false
  sequence_diagrams: false
  suggested_labels: false
  suggested_reviewers: false
  auto_review:
    enabled: true
    drafts: false
chat:
  art: false
finishing_touches:
  docstrings:
    enabled: false
  unit_tests:
    enabled: false
