accept = [200, 201, 204, 304, 403, 429]
cache = true
max_retries = 3
timeout = 20
max_concurrency = 16
exclude = [
    "http://localhost.*",
    "https://localhost.*",
    "^/.*",
    
    # Third party services that return 403 for automated requests
    "https://dev.mysql.com/.*",
    "https://www.mysql.com/.*",
    "https://www.npmjs.com/.*",
    "https://openai.com/.*",
    "https://platform.openai.com/.*",
    "https://dash.cloudflare.com/.*",
    "https://playground.ai.cloudflare.com/.*",
    "https://www.cockroachlabs.com/blog/.*",
]