[build]
command = "yarn build"
functions = "functions/"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[context.deploy-preview.environment]
GATSBY_ALGOLIA_APP_ID=""
GATSBY_ALGOLIA_SEARCH_KEY=""
GATSBY_ALGOLIA_ADMIN_API_KEY=""
GATSBY_ALGOLIA_INDEX_NAME=""

[context.branch-deploy.environment]
GATSBY_ALGOLIA_APP_ID=""
GATSBY_ALGOLIA_SEARCH_KEY=""
GATSBY_ALGOLIA_ADMIN_API_KEY=""
GATSBY_ALGOLIA_INDEX_NAME=""


