[build]
command = "npm run build"
functions = "functions/"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[context.production.environment]
INDEX_ALGOLIA = "true"

[context.deploy-preview.environment]
INDEX_ALGOLIA = "false"
DEPLOY_PREVIEW = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://www.prisma.io"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src data: 'unsafe-inline' 'unsafe-eval' https:; script-src data: 'unsafe-inline' 'unsafe-eval' https: blob:; style-src data: 'unsafe-inline' https:; img-src data: https: blob:; font-src data: https:; connect-src https: wss: blob:; media-src https: blob:; object-src https:; child-src https: data: blob:; form-action https:; block-all-mixed-content"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "microphone 'none'; geolocation 'none'"

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 200
  force = true
