[build]
command = "npm run build"
functions = "functions/"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[context.production.environment]
INDEX_ALGOLIA = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://www.prisma.io"

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 200
  force = true
