packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@argos-ci/playwright": "^6.4.1"
  "@base-ui/react": "^1.2.0"
  "@fumadocs/base-ui": "16.6.3"
  "@fumadocs/cli": "^1.2.4"
  "@kapaai/react-sdk": "^0.9.1"
  "@mixedbread/sdk": "^0.46.0"
  "@playwright/test": "^1.58.2"
  "@radix-ui/react-accordion": "^1.2.12"
  "@radix-ui/react-checkbox": "^1.3.3"
  "@radix-ui/react-collapsible": "^1.1.12"
  "@radix-ui/react-dialog": "^1.1.15"
  "@radix-ui/react-dropdown-menu": "^2.1.16"
  "@radix-ui/react-label": "^2.1.8"
  "@radix-ui/react-radio-group": "^1.3.8"
  "@radix-ui/react-separator": "^1.1.8"
  "@radix-ui/react-slider": "^1.3.6"
  "@radix-ui/react-slot": "^1.2.4"
  "@radix-ui/react-tabs": "^1.1.13"
  "@radix-ui/react-tooltip": "^1.2.8"
  "@sentry/nextjs": "^10.39.0"
  "@streamdown/code": "^1.0.3"
  "@tailwindcss/postcss": "^4.2.0"
  "@types/mdx": "^2.0.13"
  "@types/node": "^25.3.0"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "cspell": "^9.6.4"
  "dexie": "^4.3.0"
  "dexie-react-hooks": "^4.2.0"
  "fast-glob": "^3.3.3"
  "feed": "^5.2.0"
  "fumadocs-core": "16.6.3"
  "fumadocs-mdx": "14.2.7"
  "fumadocs-openapi": "^10.3.6"
  "fumadocs-ui": "npm:@fumadocs/base-ui@16.6.3"
  "gray-matter": "^4.0.3"
  "jotai": "^2.18.0"
  "lucide-react": "^0.575.0"
  "motion": "^12.34.2"
  "next": "16.1.6"
  "next-themes": "^0.4.6"
  "next-validate-link": "^1.6.3"
  "npm-to-yarn": "^3.0.1"
  "oxfmt": "^0.33.0"
  "oxlint": "^1.48.0"
  "postcss": "^8.5.6"
  "posthog-js": "^1.351.3"
  "react": "^19.2.4"
  "react-dom": "^19.2.4"
  "react-tweet": "^3.3.0"
  "remark-directive": "^4.0.0"
  "rimraf": "^6.1.3"
  "scroll-into-view-if-needed": "^3.1.0"
  "streamdown": "^2.3.0"
  "tailwind-merge": "^3.5.0"
  "tailwindcss": "^4.2.0"
  "tsx": "^4.19.0"
  "turbo": "^2.8.10"
  "tw-animate-css": "^1.4.0"
  "typescript": "^5.9.3"
  "use-stick-to-bottom": "^1.1.3"
  "vaul": "^1.1.2"
  "zod": "^4.3.6"
