name: Post Comment
description: Create or update a comment on a pull request

inputs:
  pull-request:
    description: The PR (number) to post in
    required: true
  body:
    description: The comment body (will replace if comment already exists)
    required: true
  body-includes:
    description: An optional string to search by (use this almost always)
    required: false
    default: "bot"

runs:
  using: composite
  steps:
    - name: Skip if PR is from a fork
      shell: bash
      run: |
        if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.event.pull_request.base.repo.full_name }}" ]]; then
          echo "PR is from a fork. Skipping comment steps."
          echo "IS_FORK=true" >> $GITHUB_ENV
        else
          echo "IS_FORK=false" >> $GITHUB_ENV
        fi

    - name: Find existing comment
      if: env.IS_FORK != 'true'
      uses: peter-evans/find-comment@v3
      id: find-existing
      with:
        issue-number: ${{ inputs.pull-request }}
        comment-author: "github-actions[bot]"
        body-includes: ${{ inputs.body-includes }}

    - name: Create comment
      if: env.IS_FORK != 'true' && steps.find-existing.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ inputs.pull-request }}
        body: ${{ inputs.body }}

    - name: Update comment
      if: env.IS_FORK != 'true' && steps.find-existing.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find-existing.outputs.comment-id }}
        body: ${{ inputs.body }}
        edit-mode: replace
