import { createPageMetadata } from "@/lib/page-metadata";
import Image from "next/image";
import { PrismButton, PrismButtonOutline } from "@/components/brand/prism-button";
import { RoleKicker } from "@/components/brand/role-kicker";
import { Texture } from "@/components/brand/texture";
import { cn } from "@/lib/utils";

// Rebuilt in the 2026 redesign language: wrapped-panel hero, paper surfaces,
// hairline borders, one accent (yellow: Query Insights ships with Prisma
// Postgres). Feature shots use the light asset variants from the old page so
// they sit on the light surface; copy and links carry over.

const GET_STARTED_URL = "/postgres";
const DOCS_URL = "/docs/postgres/faq#query-insights";

const FEATURES = [
  {
    title: "Actionable query visibility",
    description:
      "Query Insights groups your queries, tracks execution time and read volume, and shows you which query shapes are driving performance issues, all in one overview page.",
    imageSrc: "/illustrations/query-insights/features_1_light.svg",
    imageWidth: 672,
    imageHeight: 320,
    mobileImageSrc: "/illustrations/query-insights/features_1_mobile_light.svg",
    mobileImageWidth: 368,
    mobileImageHeight: 268,
    imageAlt:
      "Dashboard view showing query groups with execution times, read counts, and last seen timestamps",
  },
  {
    title: "From application query to SQL impact",
    description:
      "See which code-level query is causing slow responses or increased load. Prisma ORM queries are attributed to the code that ran them. All other SQL queries are visible too.",
    imageSrc: "/illustrations/query-insights/features_2_light.svg",
    imageWidth: 684,
    imageHeight: 320,
    mobileImageSrc: "/illustrations/query-insights/features_2_mobile_light.svg",
    mobileImageWidth: 368,
    mobileImageHeight: 306,
    imageAlt:
      "Split view linking a Prisma ORM query to its corresponding SQL statement and performance metrics",
  },
  {
    title: "Generate an AI prompt to fix it",
    description:
      "Query Insights generates an optimization prompt for each query group, covering likely causes like missing indexes or excessive reads. Works with any AI coding assistant.",
    imageSrc: "/illustrations/query-insights/features_3_light.svg",
    imageWidth: 684,
    imageHeight: 320,
    mobileImageSrc: "/illustrations/query-insights/features_3_mobile_light.svg",
    mobileImageWidth: 368,
    mobileImageHeight: 320,
    imageAlt:
      "AI optimization prompt generated by Prisma Query Insights for a slow query, ready to paste into an AI coding assistant",
  },
] as const;

export const metadata = createPageMetadata({
  title: "Prisma Query Insights",
  description:
    "Monitor slow queries in Prisma Postgres, understand their production impact, and generate AI-ready optimization prompts to fix performance issues faster.",
  path: "/query-insights",
  ogKicker: "Prisma Postgres",
  ogAccent: "yellow",
});

export default function QueryInsightsPage() {
  return (
    <>
      {/* Hero: wrapped-panel title band, yellow wash only (one accent per page) */}
      <section className="bg-white px-3 pt-3 sm:px-4 sm:pt-4">
        <div className="relative mx-auto max-w-[96rem] overflow-hidden rounded-[1.5rem] border border-black/[0.06] bg-white">
          <div
            aria-hidden
            className="pointer-events-none absolute inset-x-0 bottom-0 h-[16rem] overflow-hidden"
          >
            <div
              className="absolute -bottom-1/2 left-1/2 h-full w-[140%] -translate-x-1/2"
              style={{
                background: [
                  "radial-gradient(50% 62% at 30% 100%, color-mix(in srgb, var(--color-prism-yellow-300) 18%, transparent), transparent 70%)",
                  "radial-gradient(44% 54% at 56% 100%, color-mix(in srgb, var(--color-prism-yellow-100) 30%, transparent), transparent 68%)",
                  "radial-gradient(40% 48% at 78% 100%, color-mix(in srgb, var(--color-prism-yellow-400) 14%, transparent), transparent 70%)",
                ].join(","),
              }}
            />
            <div className="absolute inset-x-0 top-0 h-24 bg-gradient-to-t from-transparent to-white" />
          </div>
          <Texture opacity={0.06} blend="multiply" />

          <div className="relative px-4 sm:px-8">
            <div className="mx-auto flex max-w-site flex-col items-center pb-16 pt-32 text-center md:pb-20 md:pt-44">
              <RoleKicker color="bg-prism-yellow-300" className="justify-center">
                Query Insights
              </RoleKicker>
              <h1 className="isolate mt-4 max-w-[24ch] text-balance text-[clamp(2.5rem,4vw,3.5rem)] leading-[1.06]">
                AI-powered insights built into Prisma Postgres
              </h1>
              <p className="mt-6 max-w-[54ch] text-pretty text-lg leading-relaxed text-muted-foreground">
                Understand why your database queries are slow, see their real impact in production,
                and generate a structured AI prompt to improve them.
              </p>
              <div className="mt-8 flex flex-wrap items-center justify-center gap-4">
                <PrismButton href={GET_STARTED_URL} size="lg">
                  Get started
                </PrismButton>
                <PrismButtonOutline href={DOCS_URL} size="lg">
                  Read the docs
                </PrismButtonOutline>
              </div>
              <p className="mt-3.5 text-sm text-muted-foreground">
                Query Insights is included with Prisma Postgres at no additional cost.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Feature tour: alternating two-column rows, light shots on wash cards */}
      <section className="bg-white px-4 py-20 sm:px-8 sm:py-24">
        <div className="mx-auto flex max-w-site flex-col gap-16 sm:gap-20">
          {FEATURES.map((feature, index) => (
            <div
              key={feature.title}
              className={cn(
                "grid items-center gap-8 lg:grid-cols-2 lg:gap-16",
                index % 2 === 1 && "lg:[&>*:first-child]:order-2",
              )}
            >
              <div className="max-w-[52ch]">
                <h2 className="text-balance text-[clamp(1.5rem,2.25vw,2rem)] leading-[1.15]">
                  {feature.title}
                </h2>
                <p className="mt-4 text-pretty leading-relaxed text-muted-foreground">
                  {feature.description}
                </p>
              </div>
              <div className="rounded-2xl border border-black/[0.06] bg-prism-yellow-50 p-4 shadow-[0_1px_2px_rgba(21,21,21,0.04)] sm:p-6">
                <Image
                  src={feature.imageSrc}
                  alt={feature.imageAlt}
                  width={feature.imageWidth}
                  height={feature.imageHeight}
                  className="hidden h-auto w-full sm:block"
                />
                <Image
                  src={feature.mobileImageSrc}
                  alt={feature.imageAlt}
                  width={feature.mobileImageWidth}
                  height={feature.mobileImageHeight}
                  className="h-auto w-full sm:hidden"
                />
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Closer */}
      <section className="bg-white px-4 pb-24 sm:px-8 sm:pb-32">
        <div className="relative mx-auto flex max-w-3xl flex-col items-center gap-5 overflow-hidden rounded-2xl border border-black/[0.06] p-8 text-center sm:p-12">
          <span aria-hidden className="absolute left-0 top-0 h-1 w-full bg-prism-yellow-300" />
          <h2 className="text-[clamp(1.5rem,2.25vw,2rem)] leading-[1.15]">Built in and free</h2>
          <p className="max-w-[52ch] text-pretty text-[0.9375rem] leading-relaxed text-muted-foreground">
            Already built into Prisma Postgres. No setup, no extra cost. Open the Queries tab and
            start analyzing.
          </p>
          <div className="mt-1 flex flex-wrap items-center justify-center gap-3">
            <PrismButton href={GET_STARTED_URL}>Get started</PrismButton>
            <PrismButtonOutline href={DOCS_URL}>Read the docs</PrismButtonOutline>
          </div>
        </div>
      </section>
    </>
  );
}
