name: Create or Update Comment
on:
  workflow_call:
    inputs:
      pull-request:
        required: true
        type: number
      body:
        required: true
        type: string
      body-includes:
        required: true
        type: string
jobs:
  create-or-update-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Find existing comment
        uses: peter-evans/find-comment@v3
        id: find-existing
        with:
          issue-number: ${{ inputs.pull-request }}
          comment-author: 'github-actions[bot]'
          body-includes: ${{ inputs.body-includes }}

      - name: Create comment
        if: steps.find-existing.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ inputs.pull-request }}
          body: ${{ inputs.body }}

      - name: Update comment
        if: steps.find-existing.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-existing.outputs.comment-id }}
          body: ${{ inputs.body }}
          edit-mode: replace
