name: MDX Broken Link Checker
on: [pull_request]
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: MDX Broken Link Checker
      uses: KaiSpencer/gh-action-check-broken-links@v0
      with:
        # Required: The base URL to check links against
        # For example: /pages/foo.mdx will be checked against https://mysite.com/foo
        baseUrl: 'https://www.prisma.io'

        # Optional: Provide a directory to check for files
        # Will recurse all sub directories
        directory: 'content'