name: Broken Link Checker
on: [pull_request]
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: HashiCorp's Link Checker
        uses: hashicorp/gh-action-check-broken-links@v1
        with:
          baseUrl: 'https://prisma.io'