name: Broken Link Checker
on: [pull_request]
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: content/**/*.mdx
          concurrency: 1
          markdown: true
          fail: false
          verbosity: info